version: "3.9"

services:
  api:
    build:
      context: .
    container_name: myproject
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://alex:alex@db:5432/mydatabase

  db:
    image: postgres:15
    container_name: project2-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: alex
    volumes:
      - pgdata:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin123
  #   depends_on:
  #     - db

volumes:
  pgdata:
